from __future__ import annotations

import hashlib
import logging
import re
from datetime import UTC, datetime
from typing import Any
from email.utils import parseaddr

from google.api_core.exceptions import Conflict

from backend.core.draft_generator import (
    generate_general_response_draft,
    generate_invoice_response_draft,
    generate_si_return_draft,
)
from backend.core.repository import utcnow
from backend.core.schemas import EmailCategory, SIArtifactMetadata
from backend.core.workflows import create_category_response_draft

logger = logging.getLogger(__name__)


def extract_si_fields(
    subject: str,
    body: str,
    attachments: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Extract shipping instruction fields heuristically from subject, body, and text attachments."""
    combined_text = f"{subject}\n{body}"
    for att in attachments or []:
        text = att.get("text") or att.get("raw_text") or ""
        if text:
            combined_text += f"\n{text}"

    fields: dict[str, Any] = {
        "shipper": None,
        "consignee": None,
        "notify_party": None,
        "port_of_loading": None,
        "port_of_discharge": None,
        "container_count": None,
        "gross_weight_kg": None,
        "cargo_description": None,
    }

    # Regex patterns for shipping fields
    patterns = {
        "shipper": r"(?:shipper|exporter|from)\s*[:\-]\s*([^\n\r]+)",
        "consignee": r"(?:consignee|to)\s*[:\-]\s*([^\n\r]+)",
        "notify_party": r"(?:notify(?:\s*party)?)\s*[:\-]\s*([^\n\r]+)",
        "port_of_loading": r"(?:pol|port\s+of\s+loading|loading\s+port|origin)\s*[:\-]\s*([^\n\r]+)",
        "port_of_discharge": r"(?:pod|port\s+of\s+discharge|discharge\s+port|destination)\s*[:\-]\s*([^\n\r]+)",
        "container_count": r"(?:container(?:s)?\s*(?:count|qty|quantity)?|cntr)\s*[:\-]\s*(\d+)",
        "gross_weight_kg": r"(?:gross\s*weight|gw|total\s*weight)\s*[:\-]\s*([0-9.,]+)\s*(?:kgs?|kg|t|tons?)?",
        "cargo_description": r"(?:cargo|goods|commodity|description\s+of\s+goods)\s*[:\-]\s*([^\n\r]+)",
    }

    for key, pattern in patterns.items():
        match = re.search(pattern, combined_text, flags=re.IGNORECASE)
        if match:
            val = match.group(1).strip()
            if key == "container_count":
                try:
                    fields[key] = int(val)
                except ValueError:
                    fields[key] = 1
            elif key == "gross_weight_kg":
                clean_num = val.replace(",", "")
                try:
                    fields[key] = float(clean_num)
                except ValueError:
                    fields[key] = None
            else:
                fields[key] = val

    # Default fallback values if unparsed
    if not fields["port_of_loading"]:
        pol_match = re.search(r"\b(?:from|ex)\s+([A-Z][a-zA-Z\s]+?)(?:,\s*[A-Z]{2,})?\s+to\b", combined_text, flags=re.IGNORECASE)
        if pol_match:
            fields["port_of_loading"] = pol_match.group(1).strip()
    if not fields["port_of_discharge"]:
        pod_match = re.search(r"\bto\s+([A-Z][a-zA-Z\s]+?)(?:,\s*[A-Z]{2,})?(?:\.|\n|\r|$)", combined_text, flags=re.IGNORECASE)
        if pod_match:
            fields["port_of_discharge"] = pod_match.group(1).strip()

    return fields


def format_si_document_text(
    fields: dict[str, Any],
    case_id: str,
    subject: str,
    status: str = "DRAFT",
) -> str:
    """Format structured SI fields into a standard shipping instruction plain text document."""
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
    container_str = str(fields.get("container_count") or "TBD")
    weight_str = f"{fields.get('gross_weight_kg'):,.2f} kg" if fields.get("gross_weight_kg") is not None else "TBD"

    return f"""================================================================================
SHIPPING INSTRUCTION (SI)
Generated by ShipVerify Platform
Reference : SI-{case_id}
Subject   : {subject or 'Shipping Instruction'}
Date      : {timestamp}
Status    : {status.upper()}
================================================================================

1. SHIPPER / EXPORTER:
   {fields.get('shipper') or 'NOT SPECIFIED (PENDING CONFIRMATION)'}

2. CONSIGNEE:
   {fields.get('consignee') or 'TO ORDER (PENDING INSTRUCTION)'}

3. NOTIFY PARTY:
   {fields.get('notify_party') or 'SAME AS CONSIGNEE'}

4. PORT OF LOADING (POL):
   {fields.get('port_of_loading') or 'NOT SPECIFIED'}

5. PORT OF DISCHARGE (POD):
   {fields.get('port_of_discharge') or 'NOT SPECIFIED'}

6. CONTAINER COUNT:
   {container_str}

7. TOTAL GROSS WEIGHT:
   {weight_str}

8. CARGO & COMMODITY DESCRIPTION:
   {fields.get('cargo_description') or 'GENERAL CARGO / FREIGHT ALL KINDS (FAK)'}

================================================================================
SYSTEM VERIFICATION NOTES:
- This document was generated from customer instructions.
- Verification required before final transmission to ocean carrier.
================================================================================
END OF SHIPPING INSTRUCTION
"""


def generate_si_artifact(
    runtime: Any,
    case_id: str,
    fields: dict[str, Any] | None = None,
    reviewer: str = "system",
    expected_version: int | None = None,
) -> dict[str, Any]:
    """Generate SI text document, store artifact, and update case workflow state."""
    case = runtime.repository.get_case(case_id)
    if case is None:
        raise KeyError(case_id)

    if expected_version is not None and case.get("version") != expected_version:
        raise Conflict("Case version conflict; please refresh before generating SI")

    stored_documents = runtime.repository.list_documents(case_id)
    extracted = fields or extract_si_fields(
        case.get("subject", ""),
        case.get("body", ""),
        stored_documents,
    )

    doc_text = format_si_document_text(
        extracted,
        case_id=case_id,
        subject=case.get("subject", ""),
        status="GENERATED",
    )
    data = doc_text.encode("utf-8")
    sha256 = hashlib.sha256(data).hexdigest()

    filename = f"SI_{case_id}.txt"
    document_id = f"si-generated-{case_id}"
    gcs_uri = runtime.blobs.upload(f"cases/{case_id}/{filename}", data, content_type="text/plain")

    # Add as case document
    runtime.repository.add_document(
        case_id,
        document_id,
        {
            "filename": filename,
            "content_type": "text/plain",
            "size_bytes": len(data),
            "sha256": sha256,
            "gcs_uri": gcs_uri,
            "raw_text": doc_text,
            "extraction": {
                "document_type": "SI",
                "readable": True,
                "fields": extracted,
            },
        },
    )

    artifact_meta = SIArtifactMetadata(
        document_id=document_id,
        filename=filename,
        content_type="text/plain",
        gcs_uri=gcs_uri,
        size_bytes=len(data),
        sha256=sha256,
        status="generated",
    ).model_dump()

    workflow_state = {
        "category": EmailCategory.SI_REQUEST.value,
        "stage": "GENERATED",
        "assigned_team": "Documentation",
        "si_artifact": artifact_meta,
        "si_fields": extracted,
        "is_blocked": False,
        "updated_at": utcnow().isoformat(),
        "updated_by": reviewer,
    }

    updated = runtime.repository.update_case(
        case_id,
        {
            "workflow_state": workflow_state,
            "si_artifact": artifact_meta,
        },
        expected_version=case.get("version"),
    )
    runtime.repository.append_event(
        case_id,
        "si_artifact_generated",
        {"document_id": document_id, "filename": filename, "reviewer": reviewer},
    )
    return updated


def verify_si(
    runtime: Any,
    case_id: str,
    fields: dict[str, Any] | None = None,
    reviewer: str = "reviewer",
    note: str = "",
    expected_version: int | None = None,
) -> dict[str, Any]:
    """Mark the SI as verified and update fields if modified."""
    case = runtime.repository.get_case(case_id)
    if case is None:
        raise KeyError(case_id)
    if expected_version is not None and case.get("version") != expected_version:
        raise Conflict("Case version conflict; please refresh")

    workflow_state = dict(case.get("workflow_state") or {})
    si_fields = fields if fields is not None else workflow_state.get("si_fields", {})
    artifact = dict(workflow_state.get("si_artifact") or {})

    now = utcnow().isoformat()
    artifact["status"] = "verified"
    artifact["verified_at"] = now
    artifact["verified_by"] = reviewer

    workflow_state.update({
        "stage": "VERIFIED",
        "si_fields": si_fields,
        "si_artifact": artifact,
        "updated_at": now,
        "updated_by": reviewer,
    })

    updated = runtime.repository.update_case(
        case_id,
        {"workflow_state": workflow_state, "si_artifact": artifact},
        expected_version=case.get("version"),
    )
    runtime.repository.append_event(
        case_id,
        "si_verified",
        {"reviewer": reviewer, "note": note},
    )
    return updated


def approve_si(
    runtime: Any,
    case_id: str,
    reviewer: str = "reviewer",
    note: str = "",
    expected_version: int | None = None,
) -> dict[str, Any]:
    """Approve the verified SI document for return to requester."""
    case = runtime.repository.get_case(case_id)
    if case is None:
        raise KeyError(case_id)
    if expected_version is not None and case.get("version") != expected_version:
        raise Conflict("Case version conflict; please refresh")

    workflow_state = dict(case.get("workflow_state") or {})
    artifact = dict(workflow_state.get("si_artifact") or {})
    now = utcnow().isoformat()

    artifact["status"] = "approved"
    artifact["approved_at"] = now
    artifact["approved_by"] = reviewer

    workflow_state.update({
        "stage": "APPROVED",
        "si_artifact": artifact,
        "updated_at": now,
        "updated_by": reviewer,
    })

    updated = runtime.repository.update_case(
        case_id,
        {"workflow_state": workflow_state, "si_artifact": artifact, "review_decision": "APPROVE"},
        expected_version=case.get("version"),
    )
    runtime.repository.append_event(
        case_id,
        "si_approved",
        {"reviewer": reviewer, "note": note},
    )
    return updated


def return_si_to_requester(
    runtime: Any,
    case_id: str,
    reviewer: str = "reviewer",
    chat_id: str | None = None,
    expected_version: int | None = None,
) -> dict[str, Any]:
    """Prepare a Gmail draft returning the approved SI document attachment to the requester."""
    case = runtime.repository.get_case(case_id)
    if case is None:
        raise KeyError(case_id)
    if expected_version is not None and case.get("version") != expected_version:
        raise Conflict("Case version conflict; please refresh")

    workflow_state = dict(case.get("workflow_state") or {})
    artifact = workflow_state.get("si_artifact") or case.get("si_artifact")
    if not artifact:
        raise ValueError("Cannot return SI: document has not been generated")

    filename = artifact.get("filename", f"SI_{case_id}.txt")
    gcs_uri = artifact.get("gcs_uri")
    doc_bytes = b""
    if gcs_uri:
        doc_bytes = runtime.blobs.download(gcs_uri)
    if not doc_bytes:
        doc_bytes = format_si_document_text(
            workflow_state.get("si_fields", {}),
            case_id,
            case.get("subject", ""),
            status="APPROVED",
        ).encode("utf-8")

    subject, body = generate_si_return_draft(case, filename)
    attachments = [(filename, "text/plain", doc_bytes)]

    updated = create_category_response_draft(
        runtime.repository,
        runtime.gmail,
        runtime.telegram,
        case,
        subject=subject,
        body=body,
        attachments=attachments,
        chat_id=chat_id,
        origin="template",
    )

    now = utcnow().isoformat()
    artifact_copy = dict(artifact)
    artifact_copy["status"] = "returned"
    artifact_copy["returned_at"] = now

    workflow_state.update({
        "stage": "RETURNED",
        "si_artifact": artifact_copy,
        "updated_at": now,
        "updated_by": reviewer,
    })

    final_updated = runtime.repository.update_case(
        case_id,
        {"workflow_state": workflow_state, "si_artifact": artifact_copy},
        expected_version=updated.get("version"),
    )
    runtime.repository.append_event(
        case_id,
        "si_returned_to_requester",
        {"reviewer": reviewer, "filename": filename},
    )
    return final_updated


def route_case(
    runtime: Any,
    case_id: str,
    team: str,
    reviewer: str = "reviewer",
    expected_version: int | None = None,
) -> dict[str, Any]:
    """Route a case internally to a target team (Finance, Customer Service, etc.)."""
    case = runtime.repository.get_case(case_id)
    if case is None:
        raise KeyError(case_id)
    if expected_version is not None and case.get("version") != expected_version:
        raise Conflict("Case version conflict; please refresh")

    workflow_state = dict(case.get("workflow_state") or {})
    now = utcnow().isoformat()
    workflow_state.update({
        "stage": "ROUTED",
        "assigned_team": team,
        "updated_at": now,
        "updated_by": reviewer,
    })

    updated = runtime.repository.update_case(
        case_id,
        {"workflow_state": workflow_state, "assigned_team": team},
        expected_version=case.get("version"),
    )
    runtime.repository.append_event(
        case_id,
        "case_routed",
        {"team": team, "reviewer": reviewer},
    )
    return updated


def draft_category_response(
    runtime: Any,
    case_id: str,
    custom_instructions: str = "",
    response_text: str = "",
    reviewer: str = "reviewer",
    chat_id: str | None = None,
    expected_version: int | None = None,
) -> dict[str, Any]:
    """Generate a category response draft and save in Gmail / compose lifecycle."""
    case = runtime.repository.get_case(case_id)
    if case is None:
        raise KeyError(case_id)
    if expected_version is not None and case.get("version") != expected_version:
        raise Conflict("Case version conflict; please refresh")

    category = case.get("category") or (case.get("result") or {}).get("category")
    original_subject = case.get("subject") or "General Inquiry"
    subject = (
        original_subject
        if original_subject.lower().startswith("re:")
        else f"Re: {original_subject}"
    )

    if response_text and len(response_text.strip()) > 5:
        body = response_text.strip()
    elif category == EmailCategory.INVOICE_QUERY.value:
        subject, body = generate_invoice_response_draft(case, custom_instructions)
    elif category == EmailCategory.GENERAL.value:
        subject, body = generate_general_response_draft(case, custom_instructions)
    else:
        subject, body = generate_general_response_draft(case, custom_instructions)

    updated = create_category_response_draft(
        runtime.repository,
        runtime.gmail,
        runtime.telegram,
        case,
        subject=subject,
        body=body,
        attachments=[],
        chat_id=chat_id,
        origin="template",
    )

    workflow_state = dict(case.get("workflow_state") or {})
    workflow_state.update({
        "stage": "DRAFT_PREPARED",
        "updated_at": utcnow().isoformat(),
        "updated_by": reviewer,
    })

    final_updated = runtime.repository.update_case(
        case_id,
        {"workflow_state": workflow_state},
        expected_version=updated.get("version"),
    )
    runtime.repository.append_event(
        case_id,
        "category_response_draft_created",
        {"category": category, "reviewer": reviewer},
    )
    return final_updated


def complete_category_case(
    runtime: Any,
    case_id: str,
    reviewer: str = "reviewer",
    note: str = "",
    expected_version: int | None = None,
) -> dict[str, Any]:
    """Mark a category case as completed."""
    case = runtime.repository.get_case(case_id)
    if case is None:
        raise KeyError(case_id)
    if expected_version is not None and case.get("version") != expected_version:
        raise Conflict("Case version conflict; please refresh")

    workflow_state = dict(case.get("workflow_state") or {})
    now = utcnow().isoformat()
    workflow_state.update({
        "stage": "COMPLETED",
        "updated_at": now,
        "updated_by": reviewer,
    })

    updated = runtime.repository.update_case(
        case_id,
        {
            "workflow_state": workflow_state,
            "review_decision": "APPROVE",
        },
        expected_version=case.get("version"),
    )
    runtime.repository.append_event(
        case_id,
        "category_case_completed",
        {"reviewer": reviewer, "note": note},
    )
    return updated


def block_sender_workflow(
    runtime: Any,
    case_id: str | None,
    sender: str,
    reviewer: str = "reviewer",
    reason: str = "",
    expected_version: int | None = None,
) -> dict[str, Any]:
    """Persist sender block, attempt Gmail filter creation, and update case state."""
    raw_sender = sender.strip()
    _, email_addr = parseaddr(raw_sender)
    target_sender = email_addr or raw_sender

    filter_id: str | None = None
    if getattr(runtime.gmail, "is_configured", False):
        try:
            filter_res = runtime.gmail.create_sender_filter(target_sender)
            filter_id = filter_res.get("id")
        except Exception as exc:
            logger.warning("Failed to create Gmail filter for %s: %s", target_sender, exc)

    record = runtime.repository.block_sender(target_sender, reason=reason, filter_id=filter_id)

    if case_id:
        case = runtime.repository.get_case(case_id)
        if case:
            if expected_version is not None and case.get("version") != expected_version:
                raise Conflict("Case version conflict; please refresh")
            workflow_state = dict(case.get("workflow_state") or {})
            workflow_state.update({
                "stage": "BLOCKED",
                "is_blocked": True,
                "block_reason": reason,
                "updated_at": utcnow().isoformat(),
                "updated_by": reviewer,
            })
            updated = runtime.repository.update_case(
                case_id,
                {"workflow_state": workflow_state, "is_blocked": True},
                expected_version=case.get("version"),
            )
            runtime.repository.append_event(
                case_id,
                "sender_blocked",
                {"sender": target_sender, "reviewer": reviewer, "filter_id": filter_id},
            )
            return updated

    return record


def unblock_sender_workflow(
    runtime: Any,
    sender: str,
) -> bool:
    """Remove sender block from repository and delete Gmail filter if possible."""
    raw_sender = sender.strip()
    _, email_addr = parseaddr(raw_sender)
    target_sender = email_addr or raw_sender

    blocked_list = runtime.repository.list_blocked_senders()
    matching = next((b for b in blocked_list if b.get("sender") == target_sender.lower()), None)
    filter_id = (matching or {}).get("filter_id")

    if filter_id and getattr(runtime.gmail, "is_configured", False):
        try:
            runtime.gmail.delete_filter(filter_id)
        except Exception as exc:
            logger.warning("Failed to delete Gmail filter %s: %s", filter_id, exc)

    return runtime.repository.unblock_sender(target_sender)


def mark_not_spam_workflow(
    runtime: Any,
    case_id: str,
    reviewer: str = "reviewer",
    reclassify_as: EmailCategory = EmailCategory.GENERAL,
    expected_version: int | None = None,
) -> dict[str, Any]:
    """Unmark spam, unblock sender if blocked, and reclassify case."""
    case = runtime.repository.get_case(case_id)
    if case is None:
        raise KeyError(case_id)
    if expected_version is not None and case.get("version") != expected_version:
        raise Conflict("Case version conflict; please refresh")

    sender = case.get("sender", "")
    if sender and runtime.repository.is_sender_blocked(sender):
        unblock_sender_workflow(runtime, sender)

    workflow_state = dict(case.get("workflow_state") or {})
    now = utcnow().isoformat()
    workflow_state.update({
        "category": reclassify_as.value,
        "stage": "NOT_SPAM",
        "is_blocked": False,
        "updated_at": now,
        "updated_by": reviewer,
    })

    result = dict(case.get("result") or {})
    result["category"] = reclassify_as.value

    updated = runtime.repository.update_case(
        case_id,
        {
            "category": reclassify_as.value,
            "result": result,
            "workflow_state": workflow_state,
            "is_blocked": False,
        },
        expected_version=case.get("version"),
    )
    runtime.repository.append_event(
        case_id,
        "marked_not_spam",
        {"reviewer": reviewer, "reclassified_as": reclassify_as.value},
    )
    return updated


def build_default_workflow_state(case: dict[str, Any]) -> dict[str, Any]:
    """Build a default workflow state dictionary for a case if none is persisted."""
    cat = (case.get("category") or (case.get("result") or {}).get("category") or "GENERAL").upper()
    if cat == "SI_REQUEST" or cat == "NEW_SI_REQUEST":
        artifact = case.get("si_artifact")
        stage = "GENERATED" if artifact else "PENDING_GENERATION"
        return {
            "category": EmailCategory.SI_REQUEST.value,
            "stage": stage,
            "assigned_team": "Documentation",
            "si_artifact": artifact,
            "si_fields": {},
            "is_blocked": False,
        }
    if cat == "INVOICE_QUERY":
        return {
            "category": EmailCategory.INVOICE_QUERY.value,
            "stage": "RECEIVED",
            "assigned_team": "Finance",
            "is_blocked": False,
        }
    if cat == "SPAM":
        return {
            "category": EmailCategory.SPAM.value,
            "stage": "FLAGGED",
            "assigned_team": "Security",
            "is_blocked": bool(case.get("is_blocked")),
        }
    return {
        "category": EmailCategory.GENERAL.value,
        "stage": "RECEIVED",
        "assigned_team": "Customer Service",
        "is_blocked": False,
    }


def compute_available_actions(case: dict[str, Any], is_blocked: bool = False) -> list[str]:
    """Determine available category actions based on category and workflow stage."""
    cat = (case.get("category") or (case.get("result") or {}).get("category") or "").upper()
    state = case.get("workflow_state") or build_default_workflow_state(case)
    stage = state.get("stage", "")

    if cat in ("BL_COMPARISON", "DOCUMENT_COMPARISON"):
        return ["review", "prepare_draft", "approve", "decline"]

    if cat in ("SI_REQUEST", "NEW_SI_REQUEST"):
        if stage in ("PENDING_GENERATION", "RECEIVED", ""):
            return ["generate_si"]
        if stage == "GENERATED":
            return ["verify_si", "approve_si"]
        if stage == "VERIFIED":
            return ["approve_si", "verify_si"]
        if stage == "APPROVED":
            return ["return_si", "verify_si"]
        if stage == "RETURNED":
            return []
        return ["generate_si"]

    if cat == "INVOICE_QUERY":
        if stage in ("RECEIVED", ""):
            return ["route_finance", "draft_response"]
        if stage == "ROUTED":
            return ["draft_response", "complete"]
        if stage == "DRAFT_PREPARED":
            return ["complete", "draft_response"]
        if stage == "COMPLETED":
            return []
        return ["route_finance"]

    if cat == "GENERAL":
        if stage in ("RECEIVED", ""):
            return ["route_cs", "draft_response"]
        if stage == "ROUTED":
            return ["draft_response", "complete"]
        if stage == "DRAFT_PREPARED":
            return ["complete", "draft_response"]
        if stage == "COMPLETED":
            return []
        return ["route_cs"]

    if cat == "SPAM":
        if is_blocked or state.get("is_blocked"):
            return ["not_spam"]
        return ["block_sender", "not_spam"]

    return []
